### ISSUE TITLE
Unsafe `endif` handling

### ISSUE THREAD

**Issue by Phlarx** [codecat/ccpp#2]
There is potential for problems when there are too many or too few `#endif` directives:

When the preprocessor encounters an extra `#endif`, undefined behavior occurs due to calling `pop()` on an empty `m_stack`. `#elif` and `#else` already contain error-paths for this case.

When the preprocessor reaches EOF while `m_stack` is non-empty, it does not warn about a likely-missing `#endif`.

**Comment by codecat** [comment]
Thanks!
